---

- name: Set Policies
  rabbitmq_policy: 'name="{{ item.name }}" pattern="{{ item.pattern }}" tags="{{ item.definitions }}" priority={{ item.priority | default(0) }} state=present'
  with_items: rabbitmq.config.policies